name: My5Gcore Workflow
on: [push]

jobs:
  build:
    name: building
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
  
  test:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - name: List files Permissions
        run: ls -l
      - name: Test 5GS Procedures
        run: ./test.sh TestNon3GPP          
