name: My5Gcore Workflow
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4' # The Go version to download (if necessary) and use.
      
      - name: Get Submodules
        run: ls -l src/
      
      - name: Checkout submodules
        # You may pin to the exact commit or the version.
        # uses: textbook/git-checkout-submodule-action@0cb23c7e6a67085e1dc5e884920bd620f7b9c469
        uses: textbook/git-checkout-submodule-action@2.1.1
      
      - name: List files Permissions
        run: ls -l
        
      - name: Check GO
        run: go version
      
      - name: Install Deps and Libs
        run: pwd
      
      - name: Build NFs
        run: pwd
      
      - name: Unity Tests
        run: pwd
      
      - name: Test 5GS Procedures
        run: |
          chmod +x test.sh
          ./test.sh TestNon3GPP                
