name: My5Gcore Workflow
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Checkout Submodules
        uses: textbook/git-checkout-submodule-action@2.1.1
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'
        
      - name: Check GO
        run: |
          go version
          git --version
          echo "pwd: $(pwd)"
          echo "GOROOT: $GOROOT"
          echo "GOPATH: $GOPATH"
          
      - name: Install GO Deps
        run: | 
          go mod download
          
      - name: Packages Control Plane
        run: |
          sudo apt -y -q update
          sudo apt -y -q install wget
          
      - name: Packages User Plane
        run: | 
          sudo apt -y update
          sudo apt -y install git gcc cmake autoconf libtool pkg-config libmnl-dev libyaml-dev
          go get -u github.com/sirupsen/logrus
          git clone -b v0.1.0 https://github.com/PrinzOwO/gtp5g.git ./src/upf/build/
          cd gtp5g
          make
          sudo make install    
              
      - name: Build NFs
        run: ./build.sh
      
      - name: Test 5GS Procedures
        run: |
          chmod +x test.sh
          ./test.sh TestRegistration
          ./test.sh TestServiceRequest
          ./test.sh TestXnHandover
          ./test.sh TestDeregistration
          ./test.sh TestPDUSessionReleaseRequest
          ./test.sh TestPaging
          ./test.sh TestN2Handover
          ./test.sh TestNon3GPP                
