name: My5Gcore Workflow
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: textbook/git-checkout-submodule-action@2.1.1
      - name: Checkout Repo and Submodules
      
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'
      - name: Setup Go
        
      - name: Check GO
        run: |
          go version
          git --version
          ls -la src/amf/
          
      - name: Packages Control Plane
        run: |
          apt -y update
          apt -y install mongodb wget git
          systemctl start mongodb
          
      - name: Packages User Plane
        run: | 
          apt -y update
          apt -y install git gcc cmake autoconf libtool pkg-config libmnl-dev libyaml-dev
          go get -u github.com/sirupsen/logrus
          git clone -b v0.1.0 https://github.com/PrinzOwO/gtp5g.git ./src/upf/build/
          cd gtp5g
          make
          make install
      
      - name: Install Deps
        run: | 
          go mod download
          
              
      - name: Build NFs
        run: ./build.sh
      
      - name: Test 5GS Procedures
        run: |
          chmod +x test.sh
          ./test.sh TestNon3GPP                
