name: My5Gcore Workflow
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: building and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: List files Permissions
        run: ls -l
      - name: Test 5GS Procedures
        run: |
          ./test.sh TestNon3GPP                
